name: Build Container

on:
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Debug'
        required: false
        default: ""
        type: string
  push:
    branches: [ "main" ]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Deps
        run: |
          apt-get install -y \
          libvips-dev \
          libheif-dev \
          libwebp-dev \
          libglib2.0-dev \
          libexpat1-dev

      - name: GoGoGadgetDocker
        run: |
          echo "HEAD REF $GITHUB_HEAD_REF" 
          echo "REF $GITHUB_REF" 
          ./scripts/gogogadgetdocker.bash -l -t $BUILD_TAG
          exit $?
        env:
          BUILD_TAG: ${{ inputs.build_tag }}
