name: Build Container

on:
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Build Tag'
        required: false
        default: ""
        type: string
      do_release_build:
        description: 'Release'
        required: false
        default: false
        type: boolean
  push:
    branches: [ "main" ]

jobs:
  pretest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Deps
        run: |
          sudo apt update
          sudo apt-get install -y \
          libvips-dev \
          exiftool \
          nodejs \
          npm

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'

      - name: Launch tests
        run: |
          ./scripts/testWeblens
          exit $?

  build-container:
    runs-on: ubuntu-latest
    needs: pretest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Deps
        run: |
          sudo apt update
          sudo apt-get install -y \
          libvips-dev \
          exiftool \
          nodejs \
          npm

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'

      - name: GoGoGadgetDocker
        run: |
          sudo docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          if [ -z "$BUILD_TAG" ] && [ $RELEASE_BUILD == true ]; then
            echo "ERR BUILD_TAG must be specified when doing release build"
            exit 1
          elif [ -z "$BUILD_TAG" ] && [ "$GITHUB_REF" == "refs/heads/main" ]; then
            BUILD_TAG="amethyst-${{ github.run_number }}"
          elif [ -z "$BUILD_TAG" ]; then
            BUILD_TAG="dev-$(git rev-parse --short HEAD)"
          fi
          
          echo "Grab the new container at" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "docker.io/ethrous/weblens:$BUILD_TAG-amd64" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          
          ./scripts/gogogadgetdocker.bash -l -p -s -t $BUILD_TAG
          exit $?
        env:
          BUILD_TAG: ${{ inputs.build_tag }}
          RELEASE_BUILD: ${{ inputs.do_release_build }}
