name: Build Container

on:
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Build Tag'
        required: false
        default: ""
        type: string
  push:
    branches: [ "main" ]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Deps
        run: |
          sudo apt update
          sudo apt-get install -y \
          libvips-dev \
          libheif-dev \
          libwebp-dev \
          libglib2.0-dev \
          libexpat1-dev \
          nodejs \
          npm
          npm install -D vite

      - name: GoGoGadgetDocker
        run: |
          sudo docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          if [ -z "$BUILD_TAG" ] && [ "$GITHUB_REF" == "refs/heads/main" ]; then
            BUILD_TAG="rc-$(git rev-parse --short HEAD)"
          elif [ -z "$BUILD_TAG" ]; then
            BUILD_TAG="dev-$(git rev-parse --short HEAD)"
          fi
          echo "$BUILD_TAG-amd64" >> $GITHUB_STEP_SUMMARY
          ./scripts/gogogadgetdocker.bash -l -t $BUILD_TAG
          exit $?
        env:
          BUILD_TAG: ${{ inputs.build_tag }}
