name: Weblens Fulltest

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug'
        required: true
        default: false
        type: boolean
      remote_tests:
        description: 'Run tests with remote servers'
        required: true
        default: false
        type: boolean
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Deps
        run: |
          echo "remote tests: $REMOTE_TESTS"
          if [ $REMOTE_TESTS ]; then
            wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
            sudo apt-get update
            sudo apt-get install -y mongodb-mongosh
          fi
          sudo apt update
          sudo apt-get install -y \
          libvips-dev \
          libheif-dev \
          libwebp-dev \
          libglib2.0-dev \
          libexpat1-dev \
          exiftool
        env:
          REMOTE_TESTS: ${{ inputs.remote_tests }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'

#      - name: Build
#        run: |
#          set -x
#          go build -v -o ./weblens ./cmd/weblens/main.go

      - name: Test (No Remotes)
        if: ${{ inputs.remote_tests == false }}
        run: |
          export APP_ROOT=$(pwd)
          CONFIG_PATH=$(pwd)/config CONFIG_NAME=TEST go test -v -race ./...
          exit $?
        env:
          DEV_MODE: ${{ inputs.debug }}

      # Currently not working, need to work out env variables being reused in tests
      - name: Test (Remotes)
        if: ${{ inputs.remote_tests == true }}
        run: |
          source ./scripts/setupRemoteTests.bash
          CONFIG_PATH=$(pwd)/config CONFIG_NAME=TEST go test -v -race ./...
          exit $?
        env:
          DEV_MODE: ${{ inputs.debug }}
          REMOTE_TESTS: ${{ inputs.remote_tests }}
