name: Weblens Fulltest

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug'
        required: true
        default: false
        type: boolean
      skip_remote_tests:
        description: 'Don't run tests with remote servers'
        required: true
        default: false
        type: boolean
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Deps
        run: |
          echo "remote tests: $REMOTE_TESTS"
          if [[ "$REMOTE_TESTS" == "true" ]]; then
            wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
            sudo apt-get update
            sudo apt-get install -y mongodb-mongosh
          fi
          sudo apt update
          sudo apt-get install -y \
          libvips-dev \
          exiftool \
          nodejs \
          npm
        env:
          REMOTE_TESTS: ${{ inputs.skip_remote_tests == false }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'

      - name: Run Tests
        run: |
          echo "Including remote tests: $REMOTE_TESTS"
          ./scripts/testWeblens
          exit $?
        env:
          DEV_MODE: ${{ inputs.debug }}
          REMOTE_TESTS: ${{ inputs.skip_remote_tests == false }}

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: homebrew/actions/setup-homebrew@master

      - name: Install Deps
        run: |
          brew update
          brew install go@1.23 vips exiftool node npm
      
          brew tap mongodb/brew
          brew install mongodb-community
          brew services start mongodb-community

      - name: Run Tests
        run: |
          echo "Including remote tests: $REMOTE_TESTS"
          ./scripts/testWeblens
          exit $?
        env:
          DEV_MODE: ${{ inputs.debug }}
          REMOTE_TESTS: ${{ inputs.skip_remote_tests == false }}
