name: Weblens Fulltest

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug'
        required: true
        default: false
        type: boolean
      remote_tests:
        description: 'Run tests with remote servers'
        required: true
        default: false
        type: boolean
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Deps
        run: |
          sudo apt update
          sudo apt-get install -y \
          libvips-dev \
          libheif-dev \
          libwebp-dev \
          libglib2.0-dev \
          libexpat1-dev \
          exiftool

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'

      - name: Build
        run: |
          set -x
          go build -v -o ./weblens ./cmd/weblens/main.go

      - name: Test (No Remotes)
        if: ${{ inputs.remote_tests == 'false' }}
        run: |
          APP_ROOT=$(pwd) go test -v -race ./...
          exit $?
        env:
          DEV_MODE: ${{ inputs.debug }}

      - name: Test (Remotes)
        if: ${{ inputs.remote_tests == 'true' }}
        run: |
          source ./scripts/setupRemoteTests.bash
          REMOTE_TESTS=true APP_ROOT=$(pwd) go test -v -race ./...
          exit $?
        env:
          DEV_MODE: ${{ inputs.debug }}
