name: Weblens

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug'
        required: true
        default: false
        type: boolean
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [ '6.0', '7.0', '8.0' ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Build
        run: |
          set -x
          go build -v ./cmd/weblens/main.go

      - name: Test
        run: go test -v ./...
        env:
          - DEV_MODE: ${{ inputs.debug }}
